auctions/urls.py
from django.urls import path
from . import views
from .views import create_listing, listing_page, place_bid, watchlist_page, watchlist_btn, add_comment,close_auction


urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('create_listing/', create_listing, name='create_listing'),
    path('listing/<int:listing_id>/', listing_page, name='listing_page'),
    path('place_bid/<int:listing_id>/', place_bid, name='place_bid'),
    path('watchlist/', watchlist_page, name='watchlist_page'),
    path('watchlist_btn/<int:listing_id>/', watchlist_btn, name='watchlist_btn'),
    path('add_comment/<int:listing_id>/',add_comment, name='add_comment'),
    path('close_auction/<int:listing_id>/', close_auction, name='close_auction'),

]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Listing(models.Model):
                listing_title = models.CharField(max_length=255)
                listing_description = models.TextField()
                listing_image_url = models.URLField(blank=True, null=True)
                listing_starting_price = models.DecimalField(max_digits=10, decimal_places=2)
                seller = models.ForeignKey(User, on_delete=models.CASCADE)
                listing_category = models.CharField(max_length=255, blank=True, null=True)
                listing_current_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
                created_at = models.DateTimeField(auto_now_add=True)
                updated_at = models.DateTimeField(auto_now=True)
                watchlisted_users = models.ManyToManyField(User, blank=True, related_name="watchlist")
                winner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="won_auctions")
                # Status
                STATUS_CHOICES = [
                    ('active', 'Active'),
                    ('closed', 'Closed'),
                    ('pending', 'Pending'),
                ]
                status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')


                def __str__(self):
                    return self.listing_title
                
                def determine_winner(self):
                    # Check if there are any bids for this listing
                    if self.bids.exists():
                        # Get the highest bid
                        highest_bid = self.bids.order_by('-buyer_bid').first()

                            # Return the user who made the highest bid
                        return highest_bid.user

                    return None
                


class Comments(models.Model):
                user = models.ForeignKey(User, on_delete=models.CASCADE)
                listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='comments')
                comment_contents = models.TextField()
                created_at = models.DateTimeField(auto_now_add=True)

                def __str__(self):
                    return f"{self.user.username} - {self.listing.listing_title} - {self.created_at}"

class Bids(models.Model):
                user = models.ForeignKey(User, on_delete=models.CASCADE)
                listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='bids')
                buyer_bid = models.DecimalField(max_digits=10, decimal_places=2)
                created_at = models.DateTimeField(auto_now_add=True)

                def __str__(self):
                    return f"{self.user.username} - {self.listing.listing_title} - {self.buyer_bid}"
'''



class bids()




class comments()
'''

auctions/forms.py
from django import forms
from .models import Listing, Bids, Comments

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['listing_title', 'listing_description', 'listing_starting_price', 'listing_image_url', 'listing_category']


class BidForm(forms.ModelForm):
    class Meta:
        model = Bids
        fields = ['buyer_bid']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment_contents']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import ListingForm, BidForm, CommentForm
from django.contrib import messages
from decimal import Decimal
from django.db.models import Count
from .models import User, Listing, Bids


def index(request):
    active_listings = Listing.objects.filter(status='active').annotate(num_bids=Count('bids'))

    for listing in active_listings:
        if listing.listing_current_price is None:
            listing.listing_current_price = listing.listing_starting_price
            listing.save()


    return render(request, "auctions/index.html", {'active_listings': active_listings})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


@login_required
def create_listing(request):

    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            new_listing = form.save(commit=False)
            new_listing.seller = request.user
            new_listing.save()
            return redirect('index')
    else:
        form = ListingForm()

    return render(request, 'auctions/create_listing.html', {'form': form})



def listing_page(request, listing_id):

    listing = get_object_or_404(Listing, pk=listing_id)
    comments = listing.comments.all()
    bids = listing.bids.all()
    status = listing.status
    winner = listing.winner
    
    if status == 'closed':
        print(f"status:{status}. Winner is {winner}")
        return render(request,'auctions/closed_listing.html', {'listing':listing, 'comments':comments, 'bids':bids, 'listing_id': listing.id, 'winner': winner})
    else:
        return render(request,'auctions/listing_page.html', {'listing':listing, 'comments':comments, 'bids':bids, 'listing_id': listing.id})




def place_bid(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    bids = listing.bids.all()

    if request.method == 'POST':
        form = BidForm(request.POST)
        if form.is_valid():
            buyer_bid = form.cleaned_data['buyer_bid']

            # Check if the new bid is greater than the current price
            if buyer_bid > listing.listing_current_price:
                # Create a new bid
                bid = Bids(user=request.user, listing=listing, buyer_bid=buyer_bid)
                bid.save()

                # Update the current price
                listing.listing_current_price = buyer_bid
                listing.save()

                messages.success(request, 'Bid placed successfully.')
                return redirect('listing_page', listing_id=listing_id)
            else:
                messages.error(request, 'Bid must be greater than the current price.')

    else:
        form = BidForm()

    return render(request, 'auctions/listing_page.html', {'listing': listing, 'form': form, 'bids': bids})

@login_required
def watchlist_btn(request, listing_id):

    
    listing = get_object_or_404(Listing, pk=listing_id)
    user_watchlist = request.user.watchlist.all()


    

    if listing in user_watchlist:
            # If listing is already in watchlist, display a message
            messages.info(request, 'This listing is already in your watchlist.')
    else:
            # If not, add it to the watchlist
            request.user.watchlist.add(listing)
            messages.success(request, 'Listing added to your watchlist.')

        # Redirect to the listing_page with the listing_id
    return redirect('listing_page', listing_id=listing_id)


@login_required
def watchlist_page(request):

    user_watchlist = request.user.watchlist.all()
    
    return render(request, 'auctions/watchlist.html', {'user_watchlist': user_watchlist})


@login_required
def add_comment(request, listing_id):

    listing = get_object_or_404(Listing, pk=listing_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.listing = listing
            comment.user = request.user
            comment.save()
            return redirect('listing_page', listing_id=listing_id)
    else:
        form = CommentForm()

    return redirect('listing_page', listing_id=listing_id)

@login_required
def close_auction(request, listing_id):

    listing = get_object_or_404(Listing, pk=listing_id)

    if listing.status == 'active':
        # Change the status to 'closed'
        listing.status = 'closed'
        listing.save()

        # Determine the winner based on your logic (e.g., highest bidder)
        winner = listing.determine_winner()
        
        if winner:
            listing.winner = winner
            listing.save()
        
    return redirect('listing_page', listing_id=listing_id)

auctions/templates/auctions/closed_listing.html
{% extends 'auctions/layout.html' %}


{% block body %}
<div class="container-fluid text-center mx-auto">
  <div class="row">
    <h1 class="col"><u>{{ listing.listing_title }}</u></h1>
  </div>
  <div class="col mt-5 mx-auto text-center content">
    {% if listing.listing_image_url == None %}
      <img src="https://www.freeiconspng.com/uploads/no-image-icon-6.png" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
    {% else %}
      <img src="{{ listing.listing_image_url }}" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
    {% endif %}
    <p class="mt-5">{{ listing.listing_description }}</p>
      {% if listing.listing_current_price < listing.listing_starting_price or listing.listing_current_price == None %}
          <h3 class="mt-2"><u>${{ listing.listing_starting_price }}</u></h3>
      {% else %}
          <h3 class="mt-2"><u>${{ listing.listing_current_price }}</u></h3>
      {% endif %}
      <h1>Auction Closed:</h1>
      <h2>Listing won by: {{ listing.winner }}</h2>
      
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
          
              {% if bids %}
                  <h3><u>Total Bids: {{ bids.count }}</u></h3>
              {% else %}
                  <h3>No Bids Yet</h3>
              {% endif %}

              <ul>
                  {% for bid in bids reversed %}
                      <li>{{ bid.user.username }} - ${{ bid.buyer_bid }} - Bid Made at {{ bid.created_at }}</li>
                  {% endfor %}
              </ul>
    </div>   
    <div class="col">
      <h3 class="text-center"><u>Comments:</u></h3>
        <ol type="1">
          {% for comment in comments reversed %}
            <li>{{ comment.user.username }} - {{ comment.comment_contents }} - {{ comment.created_at }}</li>
            {% endfor %}
        </ol>
    </div>   
  </div>
</div>
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}

{% load crispy_forms_tags %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <form method="post" action="{% url 'create_listing' %}" novalidate class="col-md-6 m-5">
            {% csrf_token %}
        
            <div class="form-group">
                {{ form.listing_title|as_crispy_field }}
            </div>
        
            <div class="form-group">
                {{ form.listing_description|as_crispy_field }}
            </div>
        
            <div class="form-group">
                <label for="{{ form.starting_bid.id_for_label }}">Starting Bid ($):</label>
                {{ form.listing_starting_price|as_crispy_field }}
            </div>
        
            <div class="form-group">
                <label for="{{ form.image_url.id_for_label }}">Image URL:</label>
                {{ form.listing_image_url|as_crispy_field }}
            </div>
        
            <div class="form-group">
                <label for="{{ form.category.id_for_label }}">Category:</label>
                {{ form.listing_category|as_crispy_field }}
            </div>
        
            <button type="submit" class="btn btn-primary">List Item</button>
        </form>
    </div>
</div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    {% if active_listings %}
    <ul class="list-unstyled">
      {% for listing in active_listings %}
        <div class="card w-50 mt-5 container" style="border-width: 6px; border-color: aqua;">
        <li>
                <h5 class="card-title d-flex justify-content-center">{{ listing.listing_title }}</h5>
            <div class="d-flex justify-content-center align-items-center mb-2">
          {% if listing.listing_image_url == None %}
              <img src="https://www.freeiconspng.com/uploads/no-image-icon-6.png" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
          {% else %}
              <img src="{{ listing.listing_image_url }}" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
          {% endif %}
            </div>
            <p class="card-text m-1">{{ listing.listing_description }}</p>
            {% if listing.listing_current_price < listing.listing_starting_price %}
              <h5 class="card-subtitle m-1">Current Price: ${{ listing.listing_starting_price }}</h5>
            {% else %}
              <h5 class="card-subtitle m-1">Current Price: ${{ listing.listing_current_price }}</h5>
            {% endif %}

            <p class="m-1">Total Bids: {{ listing.num_bids }}</p>
            <p class="m-1">Created By: {{ listing.seller}}</p>
            <div class="d-flex justify-content-center align-items-center">
            <a href="{% url 'listing_page' listing.id %}" class="btn btn-primary m-1">View Listing</a>
            </div>
        </li>
        </div>
      {% endfor %}
    </ul>
  {% else %}
    <p>No active listings at the moment.</p>
  {% endif %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body style="background: #FAF5E9;">
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist_page' %}">Watchlist</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing_page.html
{% extends 'auctions/layout.html' %}


{% block body %}
<div class="container-fluid text-center mx-auto">
  <div class="row">
    <h1 class="col"><u>{{ listing.listing_title }}</u></h1>
  </div>
  <div class="col mt-5 mx-auto text-center content">
    {% if listing.listing_image_url == None %}
      <img src="https://www.freeiconspng.com/uploads/no-image-icon-6.png" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
    {% else %}
      <img src="{{ listing.listing_image_url }}" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
    {% endif %}
    <p class="mt-5">{{ listing.listing_description }}</p>
      {% if listing.listing_current_price < listing.listing_starting_price or listing.listing_current_price == None %}
          <h3 class="mt-2"><u>${{ listing.listing_starting_price }}</u></h3>
      {% else %}
          <h3 class="mt-2"><u>${{ listing.listing_current_price }}</u></h3>
      {% endif %}
    </div>
  </div>
  <div class="container-fluid">
  
    {% if user.is_authenticated %}
        {% if listing in user_watchlist %}
            <p>This listing is already in your watchlist.</p>
        {% else %}
            <form method="post" action="{% url 'watchlist_btn' listing.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary mt-2">Add to Watchlist</button>
            </form>
        {% endif %}
    {% else %}
        <h3><a class="btn btn-primary mt-2" href="{% url 'login' %}">Sign in to manage your watchlist</a></h3>
    {% endif %}

  </div>
      <div class="container-fluid">

      {% if listing.seller == user %}
        <a href="{% url 'close_auction' listing_id %}"><h5 class="btn btn-primary mt-2 mb-4">Close Auction</h5></a>
      {% endif %}
      
        
     
    
  


        {% if messages %}
          <ul class="messages h6 list-unstyled">
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>


  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <h3 class="text-center mb-4"><u>Place Your Bids</u></h3>

        {% if user.is_authenticated %}
          <form method="post" action="{% url 'place_bid' listing.id %}" class="form-inline">
            {% csrf_token %}
            <label for="id_buyer_bid">Your Bid:</label>
            <input type="number" name="buyer_bid" id="id_buyer_bid" step="0.01" required>
            <small class="form-text text-danger">
                {% if form.buyer_bid.errors %}
                  {{ form.buyer_bid.errors.0 }}
                {% endif %}
            </small>
            <button class="btn btn-primary ml-2" type="submit">Place Bid</button>
          </form>
        {% else %}
          <h3 class="text-center"><a href="{% url 'login' %}">Sign in to make a bid</a></h3>
        {% endif %}
          
              {% if bids %}
                  <h3><u>Total Bids: {{ bids.count }}</u></h3>
              {% else %}
                  <h3>No Bids Yet</h3>
              {% endif %}

              <ul>
                  {% for bid in bids reversed %}
                      <li>{{ bid.user.username }} - ${{ bid.buyer_bid }} - Bid Made at {{ bid.created_at }}</li>
                  {% endfor %}
              </ul>
    </div>   
    <div class="col">
      <h3 class="text-center"><u>Comments:</u></h3>
        {% if user.is_authenticated %}

        <h3><u>Add a Comment:</u></h3>
        <form method="post" action="{% url 'add_comment' listing.id %}" class="form-inline mb-2">
          {% csrf_token %}
          <input type="text" name="comment_contents" id="id_comment_contents" class="form-control w-50" required>
          <button class="btn btn-primary ml-2" type="submit">Add Comment</button>
        </form>
        {% endif %}


        <ol type="1">
          {% for comment in comments reversed %}
            <li>{{ comment.user.username }} - {{ comment.comment_contents }} - {{ comment.created_at }}</li>
            {% endfor %}
        </ol>
    </div>   
  </div>
</div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}

{% block body %}
  <h2>Your Watchlist</h2>
  {% if user_watchlist %}
    <ul class="list-unstyled">
      {% for listing in user_watchlist %}
        <div class="card w-50 mt-5 container" style="border-width: 6px; border-color: aqua;">
          <li>
            <h5 class="card-title d-flex justify-content-center">{{ listing.listing_title }}</h5>
            <div class="d-flex justify-content-center align-items-center mb-2">
              {% if listing.listing_image_url == None %}
                <img src="https://www.freeiconspng.com/uploads/no-image-icon-6.png" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
              {% else %}
                <img src="{{ listing.listing_image_url }}" style="width: 350px; height: 200px; align-items: center;" class="card-img-top img-fluid" alt="">
              {% endif %}
            </div>
            <p class="card-text m-1">{{ listing.listing_description }}</p>
            {% if listing.listing_current_price < listing.listing_starting_price %}
              <h5 class="card-subtitle m-1">Current Price: ${{ listing.listing_starting_price }}</h5>
            {% else %}
              <h5 class="card-subtitle m-1">Current Price: ${{ listing.listing_current_price }}</h5>
            {% endif %}
            <p class="m-1">Total Bids: {{ listing.bids.count }}</p>
            <p class="m-1">Created By: {{ listing.seller }}</p>
            <div class="d-flex justify-content-center align-items-center">
              <a href="{% url 'listing_page' listing.id %}" class="btn btn-primary m-1">View Listing</a>
            </div>
          </li>
        </div>
      {% endfor %}
    </ul>
  {% else %}
    <p>Your watchlist is empty.</p>
  {% endif %}
{% endblock %}